### ISSUE TITLE
pbdRPC

### ISSUE THREAD

**Issue by wrathematics** [ropensci/ssh#1]
You may be interested in our approach here: https://github.com/snoweye/pbdRPC

It's still evolving, and there's certainly room for multiple approaches. But saw this and just wanted to give a heads up.

**Comment by jeroenooms** [comment]
How do I setup a tunnel?
```r
> library(pbdRPC)
Loading required package: tools
> tunnel(hostname = 'dev.opencpu.org', user = 'jeroen')
cmd: /bin/ps uxww
jeroen 81032   0.0  0.0  2425444   1356   ??  R    10:35AM   0:00.01 ssh -p 22 -i /Users/jeroen/.ssh/id_rsa -N -T -L 55555:127.0.0.1:55555 jeroen@dev.opencpu.org 
```
Nothing happens?

**Comment by wrathematics** [comment]
The output line shows the local process info for the tunnel. Check `ps 81032` (in that example). The tunnel should be running.
