### ISSUE TITLE
Error when uploading a file via scp_upload()

### ISSUE THREAD

**Issue by KonstantinHoffmann** [ropensci/ssh#10]
When I upload some files via scp_upload() everything works fine, but I always get an error message in the end:

Error in scp_upload(session, files, to = "/some/path/") : 
  Failed to open file FALSE

The files are uploaded nonetheless, just this message appears every time

**Comment by jeroen** [comment]
Can you show a `traceback()` about where this error occurs?

**Comment by KonstantinHoffmann** [comment]
> scp_upload(session, "~/tmp", to="/data/users/hoffmann")
Error in scp_upload(session, "~/tmp", to = "/data/users/hoffmann") : 
  Failed to open file FALSE
> traceback()
2: .Call(C_scp_write_recursive, session, info$local, info$size, 
       info$path, to, verbose)
1: scp_upload(session, "~/tmp", to = "/data/users/hoffmann")

**Comment by jeroen** [comment]
I can't reproduce this. Can you explain, is `~/tmp` a file or directory, and is `/data/users/hoffmann` an existing directory on the server?

It would be very helpful if you can try to create an example I can reproduce locally, i.e. upload a file or directory that you create in R and use a standard target to upload (e.g. inside `/tmp/` on the server).

**Comment by jeroen** [comment]
Still cannot reproduce this. If anyone can show an example, please open a new issue.
