### ISSUE TITLE
ssh_tunnel gives "Waiting for connection on port ... " message

### ISSUE THREAD

**Issue by holek10** [ropensci/ssh#13]
I'm trying to establish SSH tunnel with port forwarding to access my PostgreSQL instance on AWS.
```
s <- ssh_connect("<username>@<jumpbox_host_IP>")
ssh_tunnel(s, port=5555, target = "<my_instance_address>:<port>")
```
I get the following message with spinning backslash/forwardslash and R session being on hold
`| Waiting for connetion on port 5555 ... ` 

It prevents me from running connection string command afterwards and start fetching the data using the following syntax from `RODBC` and `RPostgreSQL` packages.
```
conn <- RODBC::dbConnect(RPostgreSQL::dbDriver("PostgreSQL"), host = "127.0.0.1", user = "db_username>", port = 5555, dbname="<db_name>",  password = "<db_password>")
dbListTables(conn)
```

**Comment by vmorgan** [comment]
I'm having same issue, getting around by opening a different R session and connecting there. But would be great to not have to use that workaround.

**Comment by jeroen** [comment]
R is single threaded so indeed you cannot run a tunnel and a client in the same R. But you can use something like the `processx` or `callr` to start a background R process for the tunnel.

**Comment by djbirke** [comment]
@jeroen Do you have any suggestion on how to make the background process prompt for the password of an ssh key?

In my setup I'd like to use

` ssh_connect('root@1.2.3.4', keyfile = '~/.ssh/id_rsa')`

However, using your solution with `callr` or `sys` does not work, as the background process cannot raise the password prompt that unlocks the ssh key.

**Comment by jeroen** [comment]
Did you try setting your passphrase in the `password` argument in `ssh_connect ()`? If you are on linux or macos the best solution is it load your key in ssh-agent.

```
ssh_agent_add("~/.ssh/id_rsa")
```

Once the key is loaded in the agent, the you should be able to connect to your servers without passing a keyfile or passphrase.

**Comment by djbirke** [comment]
@jeroen Awesome, `ssh_agent_add` works perfect.

A final minor thing is that setting the ssh_tunnel up takes a bit, more than it takes for R to proceed. Do you have any idea how I could make sure R waits for the tunnel to be established before proceeding? At the moment I'm using `System.sleep(1)`, but this doesn't seem quite right.

```r
proc <- callr::r_bg(function(){
  session <- ssh::ssh_connect('root@1.2.3.4')
  ssh::ssh_tunnel(session, port = 5555, target = paste0('localhost:', 3306))
})
Sys.sleep(1)
con <- DBI::dbConnect(RMySQL::MySQL(),
                      username = 'script',
                      host = '127.0.0.1',
                      port = 5555,
                      password = rstudioapi::askForPassword('Database password'),
                      dbname = 'dbname')
```

**Comment by PaulC91** [comment]
Hi all, thanks for this useful discussion. I'm trying to connect to a postgres db using the code below. 

```
cmd <- 'session <- ssh::ssh_connect("user@host");ssh::ssh_tunnel(session, port = 5555, target = "127.0.0.1:5432")'
pid <- sys::r_background(args = c("-e", cmd))

con <- DBI::dbConnect(
  RPostgres::Postgres(),
  dbname = "dbname",
  host = "127.0.0.1",
  port = 5555,
  user = "user",
  password = "pwd"
)
```

The tunnel sets up fine but when I run dbConnect I get the following message in the console:

```
client connected!
\ Tunneled 145 bytes...tunnel closed!
> 
> 
Error: could not connect to server: Connection reset by peer
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5555?
Warning message:
Disconnecting from unused ssh session. Please use ssh_disconnect()
```

It seems that the tunnel is disconnecting before the connection code has a chance to run inside it? It's strange because if I open the same tunnel in the terminal and then run the connection code in R it works.

Is there any way to prevent the tunnel closing? Thanks!

**Comment by nicholas512** [comment]
> It seems that the tunnel is disconnecting before the connection code has a chance to run inside it? It's strange because if I open the same tunnel in the terminal and then run the connection code in R it works.
> 
> Is there any way to prevent the tunnel closing? Thanks!

 I had the same issue. My first problem was that R resolves file paths differently 
`"C:\\Users\\..."` worked in an interactive session, but gave the error `Error: '\U' used without hex digits in character string starting ""C:\U"` (I'm on windows).  Looking at the log, and changing `\\`s to `/` fixed the problem

try setting stdout and stderr to text files to see what's going on
``` R
sys::r_background(std_out = "C:/Users/me/tunnelout.log",
                  std_err ="C:/Users/me/tunnelout.log",
                  args = c("-e", cmd))
```

Now I find that after one database query, the tunnel closes.
