### ISSUE TITLE
How to send a command while ssh_exec_wait is not finnished.

### ISSUE THREAD

**Issue by JackHsueh** [ropensci/ssh#18]
I am using the ssh coding in a remote platform. With xshll, after connected, the prompt is `[user@ip]$`, and when I input command `SCALAstart`, it will be shift to scala platform with prompt `scala>`, and then I can input the comman of scala code to manipulate the data. But when I used the `ssh_exec_wait` in Rstudio, it also can get back the output in  consol with `scala>`, But the function is endless, and I can not sent the comman to the `scala>` line, neither the new ssh_exec_wait function, nor the console input. So can I execute command withou waiting the returns,  and execute new command  while the last comman is running. And an additional function is prefer to return the out or error  independently.

![sp181211_104433](https://user-images.githubusercontent.com/29481011/49775055-ca0eea00-fd31-11e8-9405-8d1d7197d17f.png)

**Comment by jeroen** [comment]
I don't understand what you are asking. Can you please include example R code?

**Comment by JackHsueh** [comment]
Sorry if I wasn't clear. I want to operate the remote data in EMR with [Spark Shell](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-spark-shell.html).

Typically,  I use [xshell](https://www.netsarang.com/en/xshell/) to connect to the EMR server, after connected, the to the prompt symbol is `[user@ip]$` , here I can input execute the linux command interactively. when I input command `SCALAstart` (like input `python` in windows cmd and enable python command) , it will be shift to the Spark shell with prompt symbol `scala>`, and then I can input Scala code interactively, such as `var i=1`.

When I used ssh package, it can connect to the server successfully.

```
library(ssh)
session<-ssh_connect("user@ip",keyfile="e:\\user.pem")
```

Then I can execute the linux command successfully.

`ssh_exec_wait(session, command = "date")`

![](https://raw.githubusercontent.com/JackHsueh/Pic/master/sp190227_125326.png)

But when I execute the start command of spark shell, 

`ssh_exec_wait(session,command="SCALAstart")`

it start up successfully with the symbol `scala>` . 

![](https://raw.githubusercontent.com/JackHsueh/Pic/master/49775055-ca0eea00-fd31-11e8-9405-8d1d7197d17f.png)

but I can not send new command to the server interactively. So, I guess it is because that the command `ssh_exec_wait`  is just waiting the end mark of command `SCALAstar` A red stop button in top right conner of r studio consol window, and new command of Scala code is not allowed to input. 
```
#invalid code after ssh_exec_wait(session,command="SCALAstart")
ssh_exec_wait(session, command = "var i=1")
var i=1
ssh_exec_wait(session, command = ":quit")
#in xshell, the codes below is valid after command: SCALAstart
var i=1
:quit
```
My question is "Can I input the scala code interactively during command `SCALAstart` is not finished? " like xshell, running on the spark shell prompt `scala>`, when `SCALAstart` running on the linux prompt`[user@ip]$`". (same as running python code under python prompt`>>>`  with "python interpreter command" is running on DOS CMD prompt`>` .  )

**Comment by jeroen** [comment]
Currently you can only run scripts, there is no way to setup an interactive shell. I'm actually surprised `SCALAstart` doesn't recognize that it is in a non-interactive shell and hence freezes waiting for user input.
