### ISSUE TITLE
permanent message "New server fingerprint"

### ISSUE THREAD

**Issue by MaksymTulyuk** [ropensci/ssh#19]
Each time I open a session I see the same message "New server fingerprint"
`
> ssh::ssh_connect(hostname)
New server fingerprint: c7:08:f6:9b:44:fb:ed:7f:66:aa:61:a6:d5:2b:ef:5c:71:4c:97:54
<ssh session>
connected: user@server:22
server: c7:08:f6:9b:44:fb:ed:7f:66:aa:61:a6:d5:2b:ef:5c:71:4c:97:54
`
Then the server key keeps adding to ~/.ssh/known_hosts and the message keeps popping up and the key keeps adding

Please check it

P.S. I've checked the source code and found the line 146 in src/session.c:
`
if(!ssh_is_server_known(ssh)){
    Rprintf("New server fingerprint: %s\n", ssh_get_hexa(hash, hlen));
    ssh_write_knownhost(ssh);
}
`

At the same time, libssh API stays that ssh_is_server_known is deprecated http://api.libssh.org/master/group__libssh__session.html#ga6f37e3d7bb6b938b44d6a34a76fdfa0b

**Comment by jeroen** [comment]
Hmm thanks.

Part of the problem that this api was deprecated only recently so on most servers we still need to use the old api. But it seems indeed that is not working as expected because it keeps adding keys.

**Comment by dmenne** [comment]
Still seeing this in Version 0.7.0 on Windows when I run tests with testthat. Strangely, it does not turn up when I run a single test file, only when testing the whole package. Any way to get rid of it? I tried several sink/suppressWarnings/capture.output variants with no result

```
/ |   0       | tabletNew server key: 88:e3:72:da:d8:06:28:e6:2c:e9:d6:80:7a:10:7f:f2:25:e2:35:07
| |   7       | tabletNew server key: 88:e3:72:da:d8:06:28:e6:2c:e9:d6:80:7a:10:7f:f2:25:e2:35:07
New server key: 88:e3:72:da:d8:06:28:e6:2c:e9:d6:80:7a:10:7f:f2:25:e2:35:07
\ |  10       | tabletNew server key: 88:e3:72:da:d8:06:28:e6:2c:e9:d6:80:7a:10:7f:f2:25:e2:35:07
v |  12       | tablet [3.6 s]
```
