### ISSUE TITLE
No `default_port` argument in `ssh_tunnel`

### ISSUE THREAD

**Issue by wdearden** [ropensci/ssh#25]
If I call `ssh_tunnel`, I get the following error:
```parse_host missing default_port argument with no default```

This is because there is no `default_port` argument here https://github.com/ropensci/ssh/blob/82465f39a962a7256cefdc4afa9240997c87c76c/R/tunnel.R#L21 but `parse_host` has no default (https://github.com/ropensci/ssh/blob/82465f39a962a7256cefdc4afa9240997c87c76c/R/connect.R#L68).

**Comment by jeroen** [comment]
How are you calling `ssh_tunnel` then? This works for me:

```
> session <- ssh_connect('dev.opencpu.org')
Found known server key: 1c:86:dc:b9:77:2c:74:ee:2d:00:49:6f:2e:c8:b2:61:5e:14:53:73

> ssh_tunnel(session)
- Waiting for connetion on port 5555...
```

**Comment by wdearden** [comment]
Thanks, you're right. That's what I get for dashing off a quick issue. I think I had originally called it without a port in `target` so I hit the `else` here
https://github.com/ropensci/ssh/blob/82465f39a962a7256cefdc4afa9240997c87c76c/R/connect.R#L85-L89
