### ISSUE TITLE
R Windows 3.5.3 ssh_connect 0.5 fails 

### ISSUE THREAD

**Issue by conq2230** [ropensci/ssh#26]
R Windows 3.5.3 (64Bit) ssh_connect 0.5 fails automated -- password passed via askpass earlier in program and works with Rcurl ftpUpload -- fails in ssh.  Works interactively if passwd not provided in connect string.
Works in 0.4 version.  Issue found with new user install with the 0.5 version. 

Code snippet with sever name masked:

library('askpass')
userid=askpass('Enter userid for #####:')
passw=askpass('Enter password for #####:')

session <- ssh_connect(paste(userid,"@#####.company.com",sep=''),passwd=passw)
print(session)
out <- ssh_exec_wait(session, command = cmd)
print(out)
ssh_disconnect(session)

**Comment by jeroen** [comment]
Can you add `verbose=4` to `ssh_connect()` so we can see what is going wrong?

**Comment by jeroen** [comment]
Sorry I think there was indeed a bug. It should be fixed now in the devel version:

```r
remotes::install_github("ropensci/ssh")
```

**Comment by conq2230** [comment]
Wow, that was fast.  Didn't have time to send you the email with
verbose=4.  I'll just use 0.4 until the next release.

**Comment by jeroen** [comment]
The fix has been released on cran in ssh 0.6.

**Comment by conq2230** [comment]
Thanks.  I installed 0.6 and works perfectly!
