### ISSUE TITLE
SSH key management

### ISSUE THREAD

**Issue by jeroen** [ropensci/ssh#3]
@jennybc asks if we can make key management easier. We can easily let the use generate a keypair, though I am not sure if we should write to `~/.ssh/id_rsa` or use a custom location.

It would also be nice to support something like `ssh-copy-id` to let users  store the pubkey that was used to authenticate the current session into `~/.ssh/authorized_keys` on the server. Does libssh support something like this @cryptomilk?

**Comment by jennybc** [comment]
I think inspecting current keys is also useful. In [Happy Git](http://happygitwithr.com/ssh-keys.html#do-you-already-have-keys), we try to figure out if someone has keys before creating a new pair.

**Comment by cryptomilk** [comment]
We do not exactly have a function for something like ssh-copy-id, but well it is possible to implement something like that. However libssh offers a PKI API to do all sorts of key operations.

**Comment by jeroen** [comment]
The new [credentials](https://github.com/r-lib/credentials) package contains utilities to assist with client side key management.
