### ISSUE TITLE
HTTP authenticating proxy support

### ISSUE THREAD

**Issue by espinielli** [ropensci/ssh#32]
I am behind a (corporate) authenticating proxy and have been able to establish an `ssh` connection using the `ProxyCommand` option (via [`connect.c`](https://bitbucket.org/gotoh/connect/wiki/Home) program [and environmemt variables HTTP_PROXY_USER and HTTP_PROXY_PASSWORD])

Here is an anonymized session (local/remote usr and machine/ip):

```shell
pc_usr@pc_machine MINGW64 ~
$ ssh -p 2230 -l remote_usr remote.server.org
remote_usr@remote.server.org's password:
Last login: Tue Aug 20 08:07:49 2019 from 111.111.111.111

```

I was hoping to be able to use `ropensci/ssh` R package in the same way but I saw from @hrbrmstr's changes mentioned in #16 that support for ssh config file is not implemented.
So I gave it a try by installing @hrbrmstr's fork and trying to connect:

```
> ssh::ssh_connect("remote.server.org", user = "remote_user", port = 2230, config = "~/.ssh/config", verbose = 4)
ssh_config_parse_file: Reading configuration data from C:/Users/pc_usr/.ssh/config
ssh_connect: libssh 0.8.3 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_socket_connect: Nonblocking connection socket: 1252
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: Actual timeout : 10000
ssh_connect: Timeout connecting to remote.server.org
ssh_connect: current state : 9
packet_send2: packet: wrote [len=28,padding=7,comp=20,payload=20]
Error: libssh failure at 'connect': Timeout connecting to remote.server.org
```
...and I failed miserably 😢 

Here is the ProxyCommand line in my `~/.ssh/config` (proxy's IP and user's ID changed):

```shell
ProxyCommand /c/Users/pc_usr/dev/connect.exe -H 111.22.333.444:9512 %h %p
```

In fact the error is the same as the one I had before configuring the `ProxyCommand` option, so maybe the parsing/execution of the relevant command is not working....

Any helps to find a solution to this setup or any other one is highly appreciated!
Thank you in advance for considering my request!!!!!!!!!!!

I am on MS Windows 10 PC using GitBash and ssh as follows:

```shell
$ ssh -V
OpenSSH_7.6p1, OpenSSL 1.0.2n  7 Dec 2017

$ bash --version
GNU bash, version 4.4.12(2)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by ian-flores** [comment]
@espinielli  where you able to find a solution?

**Comment by espinielli** [comment]
No workaround/solution on my side unfortunately 😢
I have to download the data I need at work from home 😱

**Comment by espinielli** [comment]
Probably due to https://github.com/ropensci/git2r/issues/395

**Comment by ian-flores** [comment]
We solved it by using the  `ssh.utils` package. It accepts a -J flag to do the ProxyJump

**Comment by espinielli** [comment]
Solution for us has been SSH tunnel (see [this SO](https://unix.stackexchange.com/a/115906/134798)).
In particular the second diagram:

![ssh-port-forwarding](https://user-images.githubusercontent.com/891692/73454724-ed9a5700-436e-11ea-88d8-df4fed1b466a.png)

```
ssh -L 123:farawayhost:456 remotehost
```
