### ISSUE TITLE
Host with more than one @ symbol

### ISSUE THREAD

**Issue by keithmcnulty** [ropensci/ssh#33]
I am having an issue with `ssh_connect()` when the username is in the form of an email address, eg:

keith@domain.com@some.host.com

Error is 

```
Error in parse_host(host, default_port = 22) : 
  host string contains multiple '@' characters
```

Is there a workaround?  Thanks :)

**Comment by jeroen** [comment]
That's unfortunate. I should add an option to pass a list instead of a string as the host.

**Comment by keithmcnulty** [comment]
That would be a nice way to handle it!

**Comment by rbvrs** [comment]
Hiya, great to see we're not alone in this! Any update or workaround on this already? Or editing of `parse_host`, setting  `if(length(x) > 2) stop("host string contains multiple '@' characters")` to `> 3` and recompiling required? Or will that likely not work due to downstream dependencies?

**Comment by jeroen** [comment]
Can you try installing the latest version:

```r
install.packages("ssh", repos = "https://dev.ropensci.org")
```
