### ISSUE TITLE
Callback function for stdout/sdterr not considered in ssh_exec_wait

### ISSUE THREAD

**Issue by Holzhauer** [ropensci/ssh#34]
Looking at ssh_exec_wait and trying to interpret the stdout stream of the remote process I found that ssh_exec_wait only checks for TRUE, empty string (leading to stdout), a string as filename (creating a connection object) or a connection object. Therefore, a callback function as listed in possible values for the std_out and std_err parameters in the doc is not considered:

```
session <- ssh::ssh_connect("dev.opencpu.org")
ssh::ssh_exec_wait(session, command = c('ls'), std_out = function(x) {print(as_text(x))})
ssh::ssh_disconnect(session)
```

**Comment by jeroen** [comment]
Thanks!
