### ISSUE TITLE
scp_upload > list_all fails if directory is provided - fixed code included

### ISSUE THREAD

**Issue by yogat3ch** [ropensci/ssh#36]
Hi @jeroen,
I noticed that list_all is tossing an error when existing directories are provided.
It looks like the `if` statement in `list_all` in scp.R:73 is the culprit:
```
if(!file.exists(path))
```
based on the code that follows, it should be:
```
if(!file.exists(path) & !dir.exists(path))
```
Not really major enough for a pull request so I just posted here.

Thanks for your work on this package!

**Comment by jeroen** [comment]
I don't think that can be correct because `file.exists()` also works for directories.

**Comment by yogat3ch** [comment]
Hi @jeroen,
Hmm, thanks for pointing this out - I figured something must be up since no one else encountered issues with this yet.
After some testing it looks like it has to do with providing a trailing slash at the end of the character input for a directory - ie:
`file.exists("~/")`
`[1] FALSE`
`dir.exists("~/")`
`[1] TRUE`

Adding the `dir.exists` accounts for the cases where the directory is supplied with a trailing slash.

**Comment by jeroen** [comment]
Ah okay, interesting. Can you send a PR then?

**Comment by yogat3ch** [comment]
Sure, shouldn't take long ~

**Comment by yogat3ch** [comment]
Looks done, closing, thank!
