### ISSUE TITLE
security risk with libssh

### ISSUE THREAD

**Issue by dracodoc** [ropensci/ssh#39]
We wanted to use `ssh` package in our organization but found libssh could have a high security risk. There are quite some news about vulnerability issues with libssh. 

Is it possible to use some alternatives? Or what need to be done to reduce the security risk with libssh?

**Comment by jeroen** [comment]
Aren't those vulnerabilities mostly about the server component of libssh though? What sort of attack do you expect when using a client?

**Comment by dracodoc** [comment]
I knew it's mostly about server component, but I'm hesitating to explain to server admins with "I knew there are vulnerabilities but we are not going to use the server component so no problem"...

That being said, I found the vulnerabilities are fixed with later version, so latest version should be fine. However in EPEL the latest version is 0.7.1 which was still vulnerable. Is there any way to install the latest version in RedHat?

**Comment by jeroen** [comment]
That's really beyond my control. You'll have to talk to the Redhat/EPEL people. However note that even if the EPEL version says 0.71, they may have packported the security fixes already.
