### ISSUE TITLE
Conda installation for this package

### ISSUE THREAD

**Issue by lc5415** [ropensci/ssh#41]
I've been unable to find a conda R ssh installation. If this isn't available, I think having one could be useful.

**Comment by jeroen** [comment]
I don't know how to do that.

**Comment by lc5415** [comment]
Hi jeroen, I've done it before for another package. I will try and do it and submit a pull request if you are cool with that

**Comment by lc5415** [comment]
Good question, I will look that up. We would need to create a conda recipe (somewhat similar to travisCI recipes or R packages documentation) then upload to a given channel in a anaconda cloud. Conda-forge has a post on how to submit packages to their channel. Also, this package is in CRAN right?

**Comment by jeroen** [comment]
Yes this is a cran package.

**Comment by lc5415** [comment]
Thanks for the reply! I've forked the repo and created a new branch to add this functionality, I am following [these guidelines](https://conda-forge.org/docs/maintainer/adding_pkgs.html) and [this helper functions](https://github.com/bgruening/conda_r_skeleton_helper) to create the conda recipe and upload it to conda forge

**Comment by lc5415** [comment]
I've now use the helper function I made to create the following recipe under [`lc5415/conda_r_skeleton_helper/r-ssh`](https://github.com/lc5415/conda_r_skeleton_helper/tree/master/r-ssh) but I am getting the following conflitcs which are hard for me to understand as I am not the author of the package and I don't know what gets sent to CRAN when the package is uploaded. 

The steps moving forward is to fix the conflicts (if possible) and to move the conda recipe to [`conda-forge/staged-recipes`](
https://github.com/conda-forge/staged-recipes)

I see you use travisCI, I will look at implementing CI for conda2travis support ([this]() seems helpful)

```bash
> conda-build r-ssh
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for r-ssh
INFO:conda_build.metadata:Attempting to finalize metadata for r-ssh
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 0.23.*, but conda is ignoring the .* and treating it as 0.23
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 0.23.*, but conda is ignoring the .* and treating it as 0.23

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
failed to parse packages from exception: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package r-base conflicts for:
r-askpass -> r-base[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=4.0,<4.1.0a0|>=3.5.1,<3.5.2.0a0']
r-credentials -> r-askpass -> r-base[version='3.1.3.*|3.2.0.*|3.2.1.*|3.2.2.*|3.3.1.*|3.3.2.*|3.4.1.*|>=3.4.2,<3.4.3a0|>=3.4.3,<3.4.4.0a0|>=3.5,<3.6.0a0|>=4.0,<4.1.0a0|>=3.5.1,<3.5.2.0a0|>=3.5.0,<3.5.1.0a0|>=3.4.1,<3.4.2.0a0']
r-base=3.5
r-credentials -> r-base[version='>=3.6,<3.7.0a0']

Package r-askpass conflicts for:
r-askpass
r-credentials -> r-askpass

Package openssl conflicts for:
r-base=3.5 -> curl -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.1.1d,<1.1.2a|>=1.1.1a,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a']
r-credentials -> r-openssl[version='>=1.2'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a']

Package libopenblas conflicts for:
r-base=3.5 -> libopenblas[version='>=0.2.20,<0.2.21.0a0']
r-askpass -> r-base[version='>=3.5,<3.6.0a0'] -> libopenblas[version='>=0.2.20,<0.2.21.0a0']
Note that strict channel priority may have removed packages required for satisfiability.
```

**Comment by jeroen** [comment]
I'm guessing the conflicts are caused by specifying the wrong version of R in the dependencies? For example an R package for R 4.0 can only depend on other R packages built with R 4.0. Maybe you need to specify a version in the dependency?

**Comment by xhochy** [comment]
@lc5415 Can you open a PR to https://github.com/conda-forge/staged-recipes with this? I guess your `conda-build` installation is defaulting to R 3.5. We don't build for that anymore on conda-forge (only R 3.6 and 4.0). Having the recipe as a PR would help to review. Meanwhile, you should try to use `conda build --R 3.6 r-ssh` to build the package locally.

**Comment by lc5415** [comment]
Thanks @xhochy for the reply, I've submitted [the PR](https://github.com/conda-forge/staged-recipes/pull/12190) now and we'll go from there!

**Comment by lc5415** [comment]
Hey @jeroen , it's bee suggested to add libssh2 to the host section the meta.yaml file for the build in macOS and Linux. I remember reading in this package documentation something against libssh2. Please advise us on this and have a look at the PR I mentioned above

**Comment by xhochy** [comment]
@lc5415 Using `libssh` is ok too, I wasn't aware that this is using `libssh` and not `libssh2`as quite some others do.

**Comment by jeroen** [comment]
`libssh` and `libssh2` are two completely different and unrelated libraries, by very different people. I didn't come up with these names. For this package you need `libssh`.

**Comment by lc5415** [comment]
Things are looking good, the package should be up in conda-forge in a few hours, also as it was mentioned in the last comments of the PR the conda version should in principle update every time the CRAN repo is updated unless the build step fails!
