### ISSUE TITLE
known_hosts?

### ISSUE THREAD

**Issue by richfitz** [ropensci/ssh#6]
I noticed that this neither modifies known_hosts or checks it (and warns if not in the list).  Is this something that should be enabled perhaps?  Is that possible with libssh?

**Comment by jeroen** [comment]
It's possible but I'm a bit wary of editing the global `~/.ssh/known_hosts` file. But maybe I shouldn't.

**Comment by richfitz** [comment]
Yeah, totally understand.  If it's not something that the underlying library can do for you then it's probably not something you want to get involved with.  But perhaps just mentioning somewhere that it's not referred to would be useful

**Comment by jeroen** [comment]
Fixed now.
