### ISSUE TITLE
SSH doesn't work with ProxyJump on Windows

### ISSUE THREAD

**Issue by Sirse** [ropensci/ssh#69]
OpenSSH client (native) works like a charm, but R doesn't connects to server with two jumps. Seems like current libssh version doesn't support ProxyJump directive. According to changelog should work with libssh 0.11.

**Comment by jeroen** [comment]
Can you please try to install the new version from https://ropensci.r-universe.dev/ssh ?

**Comment by Sirse** [comment]
Still don't work. Timeout with ProxyJump directive (trying to connect internal IP 172.*.*.* without hops?), and error with ProxyCommand directive:
libssh failure at 'connect': The libssh is built without support for proxy commands.

Probably win dll libssh should be compiled with flag?

**Comment by jeroen** [comment]
Looks like they have disabled this on Windows: https://gitlab.com/libssh/libssh-mirror/blob/master/DefineOptions.cmake#L66-68

**Comment by jeroen** [comment]
Looks like this is not supported in libssh on Windows: https://gitlab.com/libssh/libssh-mirror/blob/master/DefineOptions.cmake#L66-68

The reason is that libssh uses `fork()` to support executing server commands, which is not supported on Windows.
