### ISSUE TITLE
Unable to install : missing shared object R/library/00LOCK-ssh/00new/ssh/libs/ssh.so

### ISSUE THREAD

**Issue by m44guy** [ropensci/ssh#70]
Hello,
I try to install the package ssh but I always encounter this error :  
"** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: loading of the package or the namedspace failed for ‘ssh’ in dyn.load(file, DLLpath = DLLpath, ...) :
impossible to load the shared object '/trinity/shared/apps/cv-standard/R/4.1.0/gnu_mkl/lib64/R/library/00LOCK-ssh/00new/ssh/libs/ssh.so':
  libcrypto.so.3: cant't open the shared object ; no such file or directory"

I tried the following ways to do it within R : 
 install.packages("ssh")
or
install.packages("ssh", configure.args = c(ssh = '--no-lock') ) 

It fails 

from outside R, with the commands :
R CMD INSTALL ssh_0.9.3.tar.gz 
R CMD install --no-lock ssh_0.9.3.tar.gz 
both fail

There is a "00LOCK-ssh/00new" in the path that should not be here ; I have checked that there is no remaining 00LOCK-ssh/00new directory in the <path>/lib64/R/library directory.

Regards,
   Guy.

**Comment by jeroen** [comment]
The 00Lock is the temporary installation directory. The real problem is:

```
libcrypto.so.3: cant't open the shared object ; no such file or directory"
```

Which means your OpenSSL installation is broken/missing.

**Comment by m44guy** [comment]
thanks for the message ; I understood the reverse.
I add some lines in the "module" file to load and it works fine.
